import { FileText, ShieldCheck, Smartphone, User, Wallet } from 'lucide-react';

const cards = [
  {
    title: 'Profile & Contacts',
    description: 'View and update address, phone numbers, and emergency contacts from one place.',
    icon: User,
  },
  {
    title: 'Payslips & Taxes',
    description: 'Download recent payslips and tax forms generated by payroll.',
    icon: Wallet,
  },
  {
    title: 'Leave & Attendance',
    description: 'Check balances, apply for leave, and review attendance and timesheets.',
    icon: FileText,
  },
  {
    title: 'Assets & Policies',
    description: 'See assigned equipment, warranty info, and access company policies.',
    icon: ShieldCheck,
  },
  {
    title: 'Expenses & Reviews',
    description: 'Submit expense claims, track reimbursement, and view performance history.',
    icon: Smartphone,
  },
];

const quickLinks = [
  { label: 'Apply for Leave', action: 'Create new request' },
  { label: 'Download Last Payslip', action: 'View PDF' },
  { label: 'Submit Expense', action: 'Start claim' },
  { label: 'Upload Personal Document', action: 'Add file' },
  { label: 'Check Assets', action: 'See assignments' },
];

export default function EssPage() {
  return (
    <div className="space-y-6">
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-6 shadow-lg">
        <p className="text-xs uppercase tracking-wide text-accent">Employee Self-Service</p>
        <h1 className="text-2xl font-semibold mt-1">ESS Portal Overview</h1>
        <p className="text-sm text-slate-300 mt-2 max-w-3xl">
          A consolidated workspace for employees to manage their profile, compensation documents,
          time-off, attendance, company assets, and compliance artifacts. This page mirrors the backend ESS
          endpoints so the UI can connect directly when APIs are wired.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {cards.map((card) => (
          <div key={card.title} className="rounded-xl border border-slate-800 bg-slate-900 p-5 flex flex-col gap-3">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-400">{card.title}</p>
                <p className="text-base text-slate-200">{card.description}</p>
              </div>
              <card.icon className="text-accent" size={24} />
            </div>
            <div className="flex flex-wrap gap-2 text-xs text-slate-400">
              <span className="rounded-full border border-slate-700 px-2 py-1">AI validation</span>
              <span className="rounded-full border border-slate-700 px-2 py-1">File uploads</span>
              <span className="rounded-full border border-slate-700 px-2 py-1">Approvals</span>
            </div>
          </div>
        ))}
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        <div className="lg:col-span-2 rounded-xl border border-slate-800 bg-slate-900 p-5">
          <h2 className="text-lg font-semibold">What ships in v1</h2>
          <ul className="mt-3 space-y-2 text-sm text-slate-300 list-disc list-inside">
            <li>Profile editing with contact + emergency data.</li>
            <li>Downloads for payslips, tax certificates, and uploaded personal documents.</li>
            <li>Leave balances, applications, and attendance + timesheet views.</li>
            <li>Asset assignments, company policies, benefits and expense claim tracking.</li>
            <li>Performance review history and upcoming AI-powered compliance checks.</li>
          </ul>
        </div>
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-5 space-y-4">
          <div>
            <h3 className="text-sm font-semibold text-slate-200">Quick actions</h3>
            <div className="mt-3 space-y-2">
              {quickLinks.map((link) => (
                <button
                  key={link.label}
                  className="w-full rounded-lg border border-slate-800 bg-slate-950 px-3 py-2 text-left text-sm hover:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
                >
                  <div className="text-slate-200">{link.label}</div>
                  <div className="text-xs text-slate-400">{link.action}</div>
                </button>
              ))}
            </div>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-slate-200">AI compliance preview</h3>
            <p className="text-xs text-slate-400 mt-1">
              Hooks into visa expiry detection, probation reminders, and GOSI discrepancy alerts. Connects to the
              ESS endpoints to flag employee-specific risks.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
